[package]
name = "nakamoto_standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isds = { path = "../../isds/" }
yew = "0.19"
